<html>
 
<?php 
session_start();
$name=$_GET["name"];
// Simulating a login cookie, assuming user has logged in to set this cookie 
setcookie("login", $name);

if (empty($_SESSION['token'])) {
    if (function_exists('mcrypt_create_iv')) {
        $_SESSION['token'] = bin2hex(mcrypt_create_iv(32, MCRYPT_DEV_URANDOM));
    } else {
        $_SESSION['token'] = bin2hex(openssl_random_pseudo_bytes(32));
    }
}
$token = $_SESSION['token'];

?>

<head>
<title>CSRF</title>
</head>
<body>
<script>
var xmlhttp = new XMLHttpRequest();
var url =  "http://localhost/ex7/simple.php";
var callback = function () {
	   document.getElementById("answerdiv").innerHTML=this.responseText;
}
var call = function () {
           xmlhttp.open('GET',url, true);
	   xmlhttp.onreadystatechange = callback;
           xmlhttp.send(null);
           }
</script>
<font size="5">
This page was generated by the Server  
<button onclick= "call()"> Call the Server </button> 
</font>
<div id= answerdiv> Waiting for an answer...</div>
<!--<iframe>-->
<script src="http://localhost/ex7/attackerGadget.js"></script>
<!--</iframe>-->
</body>
</html>